### ISSUE TITLE
Ability to connect to different hubs with different app keys

### ISSUE THREAD

**Issue by DrSok** [gormanb/homebridge-connector-hub#11]
**Describe Your Problem:**

I have two different connector hubs with different app keys I want to connect to the plugin. Entering the information from one works perfectly. When entering the second ip address I get an error after restart: TypeError: Cannot read properties of undefined (reading 'currentPosition')
    at ConnectorAccessory.updateDeviceStatus (/usr/local/lib/node_modules/homebridge-connector-hub/src/connectorAccessory.ts:154:43)

Adding an extra platform by entering the json manually results in a warning when restarting: The dynamic platform ConnectorHub from the plugin homebridge-connector-hub seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!
Unfortunately this solution does not work, since the second Blinds are not showing up in Home Kit.

How can I connect both hubs to the plugin?
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.0.9
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: Raspberry Pi

**Comment by gormanb** [comment]
Hi @DrSok - from your message above, it seems that the plugin is receiving a response from the hub that does not contain the standard, expected message contents; specifically, [on this line](https://github.com/gormanb/homebridge-connector-hub/blob/115c339bb0e2566a2dbf135fee8b8114c69f1b45/src/connectorAccessory.ts#L154) it appears that the `data` field does not exist. Can you try installing the latest release `1.1.0` and turn on debug logging? I've included extra logging which should show the contents of this malformed message before the crash.

**Comment by gormanb** [comment]
A quick followup: local testing indicates that this error is what happens when an invalid connector key is supplied, which makes sense in your scenario, since you are only able to enter a single key, and so the key is invalid for your second hub. I'll put up a beta version soon which handles this scenario without crashing, and which also allows multiple keys to be configured.

**Comment by DrSok** [comment]
After some trial and error I got everything working by connecting both hubs with one controller app, so that they used the same api-key. In the plugin I used that (single) api-key and entered both ip-addresses.
