### ISSUE TITLE
Hub can have alternative deviceType 02000002 in GetDeviceListAck

### ISSUE THREAD

**Issue by hansenc0705** [gormanb/homebridge-connector-hub#14]
**Is your feature request related to a problem? Please describe:**
When adding my bridge I have one device that doesn't seem to do anything. I'm not sure what it is (maybe the hub itself) but it would be nice to hide from HomeKit.

**Describe the solution you'd like:**
Would be nice to somehow hide a device from HomeKit. For my Fans the Tuya platform allows for this but unsure how hard it is.

**Describe alternatives you've considered:**
Right now its in the default room and try to just hide it as best I can

**Comment by gormanb** [comment]
Hi @hansenc0705 - what is the extra device called? The plugin should skip over the actual hub itself, so I think it's unlikely to be that.

To (partially) hide an accessory in the Home app, you can go into its settings and deselect the "Add To Home View" box. That will remove it from the main app screen, you'll only see it if you go into one of the individual room views. If the device really does nothing, then you could also just use the "Remove Accessory" option to get rid of it entirely.

**Comment by hansenc0705** [comment]
Thanks for the reply @gormanb sorry i missed it two weeks ago. I'm not too sure what it is.

![image](https://github.com/gormanb/homebridge-connector-hub/assets/10247644/7ca367f2-9f43-4818-af84-082642f1a08b)
![image](https://github.com/gormanb/homebridge-connector-hub/assets/10247644/ee286c30-fdc6-47c1-b9c1-4fa6a09e1e58)

I have 6 blinds and this one doesnt do anything when I attempt to control it. Not much is different between a known device and this unknown besides the model and the serial number.

The serial number made me think it was the hub itself.

**Comment by hansenc0705** [comment]
@gormanb I also see this logged often

[8/8/2023, 3:05:09 PM] [ConnectorHub] Failed to sanitize device state: {
  msgType: 'ReadDeviceAck',
  mac: '34ab959160e0',
  deviceType: '02000002',
  data: { currentState: 1, numberOfDevices: 6, RSSI: -43 }
}
[8/8/2023, 3:05:14 PM] [ConnectorHub] Failed to sanitize device state: {
  msgType: 'ReadDeviceAck',
  mac: '34ab959160e0',
  deviceType: '02000002',
  data: { currentState: 1, numberOfDevices: 6, RSSI: -43 }
}
[8/8/2023, 3:05:19 PM] [ConnectorHub] Failed to sanitize device state: {
  msgType: 'ReadDeviceAck',
  mac: '34ab959160e0',
  deviceType: '02000002',
  data: { currentState: 1, numberOfDevices: 6, RSSI: -43 }
}
[8/8/2023, 3:05:24 PM] [ConnectorHub] Failed to sanitize device state: {
  msgType: 'ReadDeviceAck',
  mac: '34ab959160e0',
  deviceType: '02000002',
  data: { currentState: 1, numberOfDevices: 6, RSSI: -43 }
}

**Comment by gormanb** [comment]
Hmmm, this is interesting... it looks like the hub is being reported as `deviceType: 02000002` even though according to the documentation, this should be `02000001`. So the plugin thinks that this is a real device, since it only skips over entries that have type `02000001`. I'll update the plugin to regard both codes as denoting a wifi hub.

**Comment by gormanb** [comment]
Hi @hansenc0705: I've just published `1.1.2` which should fix this issue. You may need to delete the cached accessory for the hub device via the Homebridge UI, but the plugin should now correctly skip over the hub when discovering devices, and will not create an accessory for it.

**Comment by hansenc0705** [comment]
Thanks @gormanb just updated and removed the cached accessory. All seems well.
