### ISSUE TITLE
Not all blinds discovered on start

### ISSUE THREAD

**Issue by Leshub** [gormanb/homebridge-connector-hub#16]
**Describe Your Problem:**
First of all, thank you for the plugin.
In a few words:
Context
- I have 23 battery-powered Brel motors to operate blinds across a two-story house.
- All motors are included in the "Connector" iOS application and operate flawlessly from the application.
- I run Homebridge (latest version) on MacOS Ventura.
- I run your plugin v1.1.0.
Problem
- When I start the plugin, only a few blinds are discovered (latest was 7).  If I would restart the HB instance, additional blinds would eventually pop-up randomly.  Also, additional blinds would be added overtime, I have now reached 19 online.
- However, some of them would not be responding either from the accessories in the plugin or from Homekit.  They still respond from the "Connector" iOS app.
- I also have "failed to get position ..." and "periodic refresh failed" error messages.
Troubleshooting
- The https://github.com/dulyts/homebridge-connector-plugin immediately returns all 23 blinds.
- Could it be related to some kind of polling frequency/latency issue because of the amount of blinds ?

```
Show the Homebridge logs here, remove any sensitive information.
```
[homebridge.log(2).txt](https://github.com/gormanb/homebridge-connector-hub/files/12260234/homebridge.log.2.txt)

**Plugin Config:**
{
    "hubIps": [],
    "connectorKey": "fbb3ed3b-caaa-4e",
    "enableDebugLog": false,
    "platform": "ConnectorHub",
    "_bridge": {
        "username": "0E:61:E3:A6:6B:DA",
        "port": 54594
    }
}
```json
Show your Homebridge config.json here, remove any sensitive information.
```
{
    "bridge": {
        "name": "Homebridge D733",
        "username": "0E:29:37:C3:94:A7",
        "port": 51361,
        "pin": "645-14-202",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "hubIps": [],
            "connectorKey": "fbb3ed3b-caaa-4e",
            "enableDebugLog": false,
            "platform": "ConnectorHub",
            "_bridge": {
                "username": "0E:61:E3:A6:6B:DA",
                "port": 54594
            }
        }
    ],
    "disabledPlugins": [
        "homebridge-camera-ui"
    ]
}
**Screenshots:**

**Environment:**

* **Plugin Version**:
1.1.0
* **Homebridge Version**: 
1.6.1
* **Node.js Version**: 
18.17.0
* **NPM Version**: 
* 9.6.7
* **Operating System**: 
MacOS Ventura

**Comment by gormanb** [comment]
Hi @Leshub, thanks for raising this issue! Please try the following, in this order:
- Try entering an explicit IP for your hub in the config, and see whether that results in the blinds being discovered on startup. At present it looks like you have not provided an IP, so the blinds are being auto-discovered via multicast.
- Version 1.1.0 introduced a new discovery mechanism. If the above doesn't help, please try installing v1.0.9 of the plugin and let me know whether that allows the blinds to be discovered more effectively.

**Comment by Leshub** [comment]
> Hi @Leshub, thanks for raising this issue! Please try the following, in this order:
> 
>     * Try entering an explicit IP for your hub in the config, and see whether that results in the blinds being discovered on startup. At present it looks like you have not provided an IP, so the blinds are being auto-discovered via multicast.
_I have entered the hub IP in the config should there be a need to re-discover (e.g. current configuration lost)_

>     * Version 1.1.0 introduced a new discovery mechanism. If the above doesn't help, please try installing v1.0.9 of the plugin and let me know whether that allows the blinds to be discovered more effectively.
_I keep it in mind but will not fiddle with the currently working configuration at the moment._
_Thank you for the quick reply._
