### ISSUE TITLE
App key suddenly invalid after working for quite some time.

### ISSUE THREAD

**Issue by jeffwelsch** [gormanb/homebridge-connector-hub#18]
**Describe Your Problem:**

I've been using the plugin for some time with an Amp motorization hub for 3 day blinds.  You have implemented the top down/bottom up capabilities to help control my devices as well -- much appreciated.

Yesterday, without any changes, I noticed that I am receiving error messages around the app key being invalid, but this has not changed.  I have confirmed the app key matches that produced in the application.

**Logs:**

[8/10/2023, 7:23:04 AM] [homebridge-connector-hub] Error received from hub. App key may be invalid: {
  msgType: 'ReadDeviceAck',
  mac: 'a4e57cbe69fb0008',
  deviceType: '10000001',
  msgID: '20230810142300745',
  data: {
    type: 9,
    exist_subid: 1,
    operation_B: 2,
    currentPosition_B: 100,
    currentState_B: 3,
    voltageMode: 1,
    batteryLevel_B: 756,
    wirelessMode: 1,
    RSSI: -92
  }
}
[8/10/2023, 7:23:08 AM] [homebridge-connector-hub] Error received from hub. App key may be invalid: {
  msgType: 'ReadDeviceAck',
  mac: 'a4e57cbe69fb0001',
  deviceType: '10000001',
  msgID: '20230810142305242',
  data: {
    type: 9,
    exist_subid: 1,
    operation_B: 2,
    currentPosition_B: 3,
    currentState_B: 3,
    voltageMode: 1,
    batteryLevel_B: 767,
    wirelessMode: 1
  }
}
[8/10/2023, 7:23:08 AM] [homebridge-connector-hub] Error received from hub. App key may be invalid: {
  msgType: 'ReadDeviceAck',
  mac: 'a4e57cbe69fb0002',
  deviceType: '10000001',
  msgID: '20230810142305332',
  data: {
    type: 9,
    exist_subid: 1,
    operation_B: 2,
    currentPosition_B: 0,
    currentState_B: 3,
    voltageMode: 1,
    batteryLevel_B: 808,
    wirelessMode: 1,
    RSSI: -91
  }
}
[8/10/2023, 7:23:08 AM] [homebridge-connector-hub] Error received from hub. App key may be invalid: {
  msgType: 'ReadDeviceAck',
  mac: 'a4e57cbe69fb0004',
  deviceType: '10000001',
  msgID: '20230810142305400',
  data: {
    type: 9,
    exist_subid: 1,
    operation_B: 2,
    currentPosition_B: 100,
    currentState_B: 3,
    voltageMode: 1,
    batteryLevel_B: 809,
    wirelessMode: 1,
    RSSI: -94
  }
}

**Plugin Config:**

       {
            "hubIps": [],
            "connectorKey": "90254069-51a8-40",
            "enableDebugLog": false,
            "_bridge": {
                "username": "Mac address",
                "port": 39200
            },
            "platform": "ConnectorHub"
        }

**Environment:**

* **Plugin Version**: homebridge-connector-hub v1.1.2
* **Homebridge Version**: 1.6.1
* **Node.js Version**: v18.17.1
* **NPM Version**: 9.6.7>
* **Operating System**: UBUNTU_CODENAME=jammy

**Comment by gormanb** [comment]
Hi @jeffwelsch - I believe this may be a bug that was introduced in version `1.1.2`. There's a `1.1.3-beta.0` available now, can you give that a try and confirm whether it fixes this issue?

**Comment by jeffwelsch** [comment]
@gormanb that patch has addressed the issue and I have not had an invalid key error since installing that version many hours ago.
