### ISSUE TITLE
Thank you & feature request: de-register accessories that have been removed in Connector app

### ISSUE THREAD

**Issue by lolgas** [gormanb/homebridge-connector-hub#23]
I could not find an appropriate way to contact you but this plugin for homebridge is saving my ass. I bought ~50 of Smart Wings Thread for HomeKit blinds and found that the thread protocol is in its infancy and Apple's implementation leaves a lot to be desired. Basically I had a lot of paperweights on my hands, until Smart Wings sent me this hub, which unfortunately doesn't natively integrate to HomeKit. Now with this plugin it does. Please tell me how I can buy you a beer, really appreciate you!

**Comment by lolgas** [comment]
While I'm here I did run into one issue. I deleted an accessory from connector app after having already synced it into homebridge. For some reason the plugin doesn't recognize its gone.. so I have a ghost accessory in homekit that doesn't work or control anything. Any ideas? I restarted the hub and restarted homebridge to no effect.

**Comment by gormanb** [comment]
Hi @lolgas - many thanks for the kind words! 😄 

The plugin does not proactively de-register devices because, during the plugin's device discovery process, it cannot determine with 100% confidence that the device has actually been removed - it may just be that there's a network issue preventing that device from being reported, or the hub is slow to respond. A future release may be able to improve upon this behaviour, but for now you should be able to just remove the accessory from the Home app.

**Comment by lolgas** [comment]
Sadly there is no option in Home app to remove the accessory, I don’t believe it allows you to remove devices that are otherwise added via a bridge or hub.

**Comment by gormanb** [comment]
Ah, you're quite right. But you should be able to remove the stale accessory via Homebridge by [using the "Remove Single Cached Accessory" option in the Settings menu](https://www.reddit.com/r/homebridge/comments/sdirig/is_there_a_way_to_clear_out_cached_accessories/).

**Comment by lolgas** [comment]
Thanks that worked perfectly!

**Comment by gormanb** [comment]
Hi @lolgas - I've just published a new beta version, `1.1.4-beta.0`, which should have the ability to remove stale devices automatically. Would it be possible for you to test it and confirm it's working as expected? If so, please do the following:
- Install the new beta plugin version
- Re-add the device that you removed on the connector app and wait for it to appear in the plugin and Home app (should take ~5 minutes)
- Remove the device from the connector app again
- Wait to see if it is removed from the plugin and Home app (may again take ~5 minutes)

**Comment by lolgas** [comment]
Hey for what its worth, it did remove the stale device when I conducted your test! Sorry for the delay.
