### ISSUE TITLE
Suppress Periodic Refresh Failed Message

### ISSUE THREAD

**Issue by hansenc0705** [gormanb/homebridge-connector-hub#25]
**Describe The Bug:**
Noticed in my logs a scrolling Periodic Refresh Failed Message

**To Reproduce:**
Unsure when it started.

**Expected behavior:**
Is it an OK error, if so any way to suppress it?

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
        {
            "hubIps": [],
            "connectorKey": "XXXXXXXXXXX",
            "enableDebugLog": false,
            "platform": "ConnectorHub"
        },
```

**Screenshots:**
![image](https://github.com/gormanb/homebridge-connector-hub/assets/10247644/f8062ac7-bbc8-4b42-9267-310471c9555a)

**Environment:**

* **Plugin Version**: homebridge-connector-hub v1.1.3
* **Homebridge Version**: v1.6.1
* **Node.js Version**: v18.13.0
* **NPM Version**: 
* **Operating System**: Docker Ubuntu Focal Fossa (20.04.5 LTS)

**Comment by gormanb** [comment]
Hi @hansenc0705,

Yes, this message is OK; it just means that the device was slow to respond to one of the periodic pings that the plugin sends. The plugin does this every 5 seconds, so the device's status will simply be refreshed on the next ping. In the next release I'll be making this message a "debug" message, so it will only show up if you turn on the "Debug Logging" option in the config.

**Comment by hansenc0705** [comment]
Thanks @gormanb
