### ISSUE TITLE
[homebridge-connector-hub] Device discovery failed to reach hub 238.0.0.18, retrying...

### ISSUE THREAD

**Issue by milanmitosinka** [gormanb/homebridge-connector-hub#29]
any thoughts on this ? I havent changed anytihng on NAS / Homebridge / Wifi / Connector bridge....

**Comment by gormanb** [comment]
Hi @milanmitosinka: `238.0.0.18` is the multicast IP address that the plugin will use to contact the hub if no explicit IP address is provided. However, on some machines or in some network configurations, it may not be able to reach the hub via multicast. I'd suggest going into the "Advanced Settings" section of the plugin's config UI and adding your hub's actual IP address, that may solve the issue.

**Comment by gormanb** [comment]
@milanmitosinka: any update on this? Did setting the IP help?

**Comment by milanmitosinka** [comment]
Yes it worked. Added fixed ip to hub and it works. It solved some random "unavailability" of blinds in homekit app as well. Thanks !

**Comment by lolgas** [comment]
I just wanted to comment and say that I also have had this issue and switching to an explicit device LAN IP fixed the issue with this error message.
